<?php
/**
 * Web-based Configuration Editor for Calendar Tag Scheduler
 *
 * Provides a simple web interface to edit config/config.php
 */

$configFile = __DIR__ . '/config/config.php';
$configExampleFile = __DIR__ . '/config/config.example.php';

// Load current config or use example
if (file_exists($configFile)) {
    $config = require $configFile;
} elseif (file_exists($configExampleFile)) {
    $config = require $configExampleFile;
} else {
    die("ERROR: No configuration file found.");
}

$message = '';
$messageType = '';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        // Parse slots
        $slots = [];
        if (isset($_POST['slot_names']) && is_array($_POST['slot_names'])) {
            foreach ($_POST['slot_names'] as $index => $slotName) {
                if (!empty(trim($slotName))) {
                    $actions = isset($_POST['slot_actions'][$index]) ? $_POST['slot_actions'][$index] : [];
                    $slots[trim($slotName)] = $actions;
                }
            }
        }

        // Parse priority to period mapping
        $priorityToPeriod = [];
        if (isset($_POST['priority']) && is_array($_POST['priority'])) {
            foreach ($_POST['priority'] as $index => $priority) {
                $period = isset($_POST['period'][$index]) ? intval($_POST['period'][$index]) : 2;
                $priorityToPeriod[intval($priority)] = $period;
            }
        }

        // Parse allowSameDayRepetition
        $allowSameDayRepetition = isset($_POST['allowSameDayRepetition']) ? true : false;

        // Parse tags
        $tags = [];
        if (isset($_POST['tag_names']) && is_array($_POST['tag_names'])) {
            foreach ($_POST['tag_names'] as $index => $tagName) {
                if (!empty(trim($tagName))) {
                    $tags[] = [
                        'name' => trim($tagName),
                        'action' => isset($_POST['tag_actions'][$index]) ? trim($_POST['tag_actions'][$index]) : '',
                        'type' => isset($_POST['tag_types'][$index]) ? trim($_POST['tag_types'][$index]) : '',
                        'channel' => isset($_POST['tag_channels'][$index]) ? trim($_POST['tag_channels'][$index]) : '',
                        'priority' => isset($_POST['tag_priorities'][$index]) ? intval($_POST['tag_priorities'][$index]) : 3,
                    ];
                }
            }
        }

        // Build config array
        $newConfig = [
            'slots' => $slots,
            'priorityToPeriod' => $priorityToPeriod,
            'allowSameDayRepetition' => $allowSameDayRepetition,
            'tags' => $tags,
        ];

        // Generate PHP code
        $configCode = "<?php\n";
        $configCode .= "/**\n";
        $configCode .= " * Configuration file for Calendar Tag Scheduler\n";
        $configCode .= " * Generated by config-editor.php on " . date('Y-m-d H:i:s') . "\n";
        $configCode .= " */\n\n";
        $configCode .= "return " . var_export($newConfig, true) . ";\n";

        // Save to file
        if (file_put_contents($configFile, $configCode)) {
            $message = "Configuration saved successfully to config/config.php!";
            $messageType = 'success';
            // Reload config
            $config = require $configFile;
        } else {
            $message = "ERROR: Failed to write to config/config.php. Check file permissions.";
            $messageType = 'error';
        }
    } catch (Exception $e) {
        $message = "ERROR: " . $e->getMessage();
        $messageType = 'error';
    }
}

// Extract data for form
$slots = $config['slots'] ?? [];
$priorityToPeriod = $config['priorityToPeriod'] ?? [];
$allowSameDayRepetition = $config['allowSameDayRepetition'] ?? true;
$tags = $config['tags'] ?? [];

// Extract available actions from tags (dynamic, user-defined)
$availableActions = [];
foreach ($tags as $tag) {
    if (!empty($tag['action']) && !in_array($tag['action'], $availableActions)) {
        $availableActions[] = $tag['action'];
    }
}

// Add commonly used actions if not already present
$commonActions = ['EDU', 'R', 'A', 'V', 'D'];
foreach ($commonActions as $action) {
    if (!in_array($action, $availableActions)) {
        $availableActions[] = $action;
    }
}

sort($availableActions);
?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendar Tag Scheduler - Configuration Editor</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: #f5f5f5;
            padding: 20px;
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        h1 {
            color: #333;
            margin-bottom: 10px;
            font-size: 28px;
        }

        .subtitle {
            color: #666;
            margin-bottom: 30px;
            font-size: 14px;
        }

        .message {
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 4px;
            font-weight: 500;
        }

        .message.success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }

        .message.error {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }

        .section {
            margin-bottom: 40px;
        }

        .section h2 {
            color: #444;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #e0e0e0;
            font-size: 20px;
        }

        .section p {
            color: #666;
            margin-bottom: 15px;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        th {
            background: #f8f9fa;
            padding: 12px;
            text-align: left;
            font-weight: 600;
            color: #333;
            border: 1px solid #dee2e6;
        }

        td {
            padding: 10px 12px;
            border: 1px solid #dee2e6;
        }

        input[type="text"],
        input[type="number"],
        select {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
        }

        input[type="text"]:focus,
        input[type="number"]:focus,
        select:focus {
            outline: none;
            border-color: #4CAF50;
        }

        input[type="checkbox"] {
            width: 20px;
            height: 20px;
            cursor: pointer;
        }

        .checkbox-group {
            display: flex;
            gap: 15px;
            flex-wrap: wrap;
        }

        .checkbox-group label {
            display: flex;
            align-items: center;
            gap: 5px;
            cursor: pointer;
        }

        .btn {
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
            font-weight: 500;
            transition: background-color 0.2s;
        }

        .btn-primary {
            background: #4CAF50;
            color: white;
        }

        .btn-primary:hover {
            background: #45a049;
        }

        .btn-secondary {
            background: #6c757d;
            color: white;
        }

        .btn-secondary:hover {
            background: #5a6268;
        }

        .btn-danger {
            background: #dc3545;
            color: white;
            padding: 5px 10px;
            font-size: 12px;
        }

        .btn-danger:hover {
            background: #c82333;
        }

        .actions {
            display: flex;
            gap: 10px;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #e0e0e0;
        }

        .help-text {
            font-size: 12px;
            color: #666;
            margin-top: 5px;
        }

        .tag-row td {
            vertical-align: middle;
        }

        .remove-btn-cell {
            width: 80px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Calendar Tag Scheduler</h1>
        <p class="subtitle">Configuration Editor</p>

        <?php if ($message): ?>
            <div class="message <?php echo $messageType; ?>">
                <?php echo htmlspecialchars($message); ?>
            </div>
        <?php endif; ?>

        <form method="POST" id="configForm">

            <!-- Tags Section -->
            <div class="section">
                <h2>Tags</h2>
                <p>Define content tags with their properties. You can use existing actions or type custom ones (e.g., EDU, R, A, V, D, etc.)</p>

                <table id="tagsTable">
                    <thead>
                        <tr>
                            <th style="width: 25%;">Name</th>
                            <th style="width: 15%;">Action</th>
                            <th style="width: 15%;">Type</th>
                            <th style="width: 15%;">Channel</th>
                            <th style="width: 10%;">Priority</th>
                            <th style="width: 80px;">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tags as $tag): ?>
                        <tr class="tag-row">
                            <td>
                                <input type="text" name="tag_names[]" value="<?php echo htmlspecialchars($tag['name']); ?>" required>
                            </td>
                            <td>
                                <input type="text" name="tag_actions[]" list="actionsList" value="<?php echo htmlspecialchars($tag['action'] ?? ''); ?>" required placeholder="e.g., EDU, R, A, V, D">
                            </td>
                            <td>
                                <input type="text" name="tag_types[]" value="<?php echo htmlspecialchars($tag['type'] ?? ''); ?>">
                            </td>
                            <td>
                                <input type="text" name="tag_channels[]" value="<?php echo htmlspecialchars($tag['channel'] ?? ''); ?>">
                            </td>
                            <td>
                                <input type="number" name="tag_priorities[]" value="<?php echo $tag['priority']; ?>" min="1" max="10" required>
                            </td>
                            <td class="remove-btn-cell">
                                <button type="button" class="btn btn-danger" onclick="removeRow(this)">Remove</button>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <!-- Datalist for action suggestions -->
                <datalist id="actionsList">
                    <?php foreach ($availableActions as $action): ?>
                        <option value="<?php echo htmlspecialchars($action); ?>">
                    <?php endforeach; ?>
                </datalist>

                <button type="button" class="btn btn-secondary" onclick="addTagRow()">Add Tag</button>
            </div>

            <!-- Time Slots Section -->
            <div class="section">
                <h2>Time Slots</h2>
                <p>Define time slots and their allowed actions. Common actions: EDU = Study, R = Read, A = Listen/Audio, V = View/Watch, D = Develop. You can also define custom actions in your tags.</p>

                <table id="slotsTable">
                    <thead>
                        <tr>
                            <th style="width: 30%;">Slot Name</th>
                            <th>Allowed Actions</th>
                            <th style="width: 80px;">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($slots as $slotName => $actions): ?>
                        <tr class="slot-row">
                            <td>
                                <input type="text" name="slot_names[]" value="<?php echo htmlspecialchars($slotName); ?>" required>
                            </td>
                            <td>
                                <div class="checkbox-group">
                                    <?php foreach ($availableActions as $action): ?>
                                        <label>
                                            <input type="checkbox" name="slot_actions[<?php echo count($slots) - array_search($slotName, array_keys($slots)) - 1; ?>][]" value="<?php echo $action; ?>" <?php echo in_array($action, $actions) ? 'checked' : ''; ?>>
                                            <?php echo $action; ?>
                                        </label>
                                    <?php endforeach; ?>
                                </div>
                            </td>
                            <td class="remove-btn-cell">
                                <button type="button" class="btn btn-danger" onclick="removeRow(this)">Remove</button>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <button type="button" class="btn btn-secondary" onclick="addSlotRow()">Add Slot</button>
            </div>

            <!-- Priority to Period Mapping -->
            <div class="section">
                <h2>Priority to Period Mapping</h2>
                <p>Define how many days should pass between repetitions for each priority level (Priority 5 = highest, Priority 1 = lowest)</p>

                <table id="priorityTable">
                    <thead>
                        <tr>
                            <th style="width: 30%;">Priority Level</th>
                            <th>Period (Days)</th>
                            <th style="width: 80px;">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        krsort($priorityToPeriod); // Sort by priority descending
                        foreach ($priorityToPeriod as $priority => $period):
                        ?>
                        <tr>
                            <td>
                                <input type="number" name="priority[]" value="<?php echo $priority; ?>" min="1" max="10" required>
                            </td>
                            <td>
                                <input type="number" name="period[]" value="<?php echo $period; ?>" min="1" required>
                            </td>
                            <td class="remove-btn-cell">
                                <button type="button" class="btn btn-danger" onclick="removeRow(this)">Remove</button>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <button type="button" class="btn btn-secondary" onclick="addPriorityRow()">Add Priority Level</button>
            </div>

            <!-- Same Day Repetition -->
            <div class="section">
                <h2>Same Day Repetition</h2>
                <label style="display: flex; align-items: center; gap: 10px;">
                    <input type="checkbox" name="allowSameDayRepetition" value="1" <?php echo $allowSameDayRepetition ? 'checked' : ''; ?>>
                    Allow same tag to appear multiple times in one day
                </label>
                <p class="help-text">If unchecked, each tag will appear at most once per day</p>
            </div>

            <!-- Actions -->
            <div class="actions">
                <button type="submit" class="btn btn-primary">Save Configuration</button>
                <a href="scheduler.php" class="btn btn-secondary" style="text-decoration: none; display: inline-block;">View Schedule</a>
            </div>
        </form>
    </div>

    <script>
        let slotIndex = <?php echo count($slots); ?>;

        function addSlotRow() {
            const tbody = document.querySelector('#slotsTable tbody');
            const row = document.createElement('tr');
            row.className = 'slot-row';
            row.innerHTML = `
                <td>
                    <input type="text" name="slot_names[]" required>
                </td>
                <td>
                    <div class="checkbox-group">
                        <?php foreach ($availableActions as $action): ?>
                            <label>
                                <input type="checkbox" name="slot_actions[${slotIndex}][]" value="<?php echo $action; ?>">
                                <?php echo $action; ?>
                            </label>
                        <?php endforeach; ?>
                    </div>
                </td>
                <td class="remove-btn-cell">
                    <button type="button" class="btn btn-danger" onclick="removeRow(this)">Remove</button>
                </td>
            `;
            tbody.appendChild(row);
            slotIndex++;
        }

        function addPriorityRow() {
            const tbody = document.querySelector('#priorityTable tbody');
            const row = document.createElement('tr');
            row.innerHTML = `
                <td>
                    <input type="number" name="priority[]" min="1" max="10" required>
                </td>
                <td>
                    <input type="number" name="period[]" min="1" required>
                </td>
                <td class="remove-btn-cell">
                    <button type="button" class="btn btn-danger" onclick="removeRow(this)">Remove</button>
                </td>
            `;
            tbody.appendChild(row);
        }

        function addTagRow() {
            const tbody = document.querySelector('#tagsTable tbody');
            const row = document.createElement('tr');
            row.className = 'tag-row';
            row.innerHTML = `
                <td>
                    <input type="text" name="tag_names[]" required>
                </td>
                <td>
                    <input type="text" name="tag_actions[]" list="actionsList" required placeholder="e.g., EDU, R, A, V, D">
                </td>
                <td>
                    <input type="text" name="tag_types[]">
                </td>
                <td>
                    <input type="text" name="tag_channels[]">
                </td>
                <td>
                    <input type="number" name="tag_priorities[]" value="3" min="1" max="10" required>
                </td>
                <td class="remove-btn-cell">
                    <button type="button" class="btn btn-danger" onclick="removeRow(this)">Remove</button>
                </td>
            `;
            tbody.appendChild(row);
        }

        function removeRow(button) {
            const row = button.closest('tr');
            row.remove();
        }
    </script>
</body>
</html>
